project:
  type: website

website:
  title: "dnc-webtest"
  navbar:
    left:
      - href: index.qmd
        text: At a Glance
      - about.qmd
      - dashboard.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

